### ISSUE TITLE
ServiceUI.exe only accept up to 10  characters

### ISSUE THREAD

**Issue by KhunakornSinthudech** [okieselbach/Intune#1]
Dear okieselbach,

Bitlocker pin ServiceUI.exe only accept up to 10  characters
It's not allow to click OK if the pin go beyond that number.

Do you mind to share the source code ?

Thanks.

**Comment by okieselbach** [comment]
Oh I'm sorry I totally missed the issue. Actually I don't have the source code. It is a helper from the Microsoft Deployment Toolkit (MDT). Sorry!
