### ISSUE TITLE
-GroupTag isnt working since last week anymore!

### ISSUE THREAD

**Issue by mvthul** [okieselbach/Intune#8]

**Comment by mvthul** [comment]
Get-WindowsAutoPilotInfo.ps1 -Online -GroupTag #### 

Results in a azure ad joined device in intune but the grouptag stays empty

**Comment by kzelazny90** [comment]
Please fix these issue - the same situation in our environment. 

Waiting for 1 of 1 to be assigned - the status has been on for several hours and still the GroupTag value is not properly assigned to the device...

**Comment by okieselbach** [comment]
I think they fixed the back end...

Resolved - Unable to assign group tags with the WindowsAutopilotIntune PowerShell script
https://techcommunity.microsoft.com/t5/intune-customer-success/resolved-unable-to-assign-group-tags-with-the/ba-p/2233247
